[project]
name = "qgsw"
version = "5.0.0"
description = ""
authors = [{name="Gaétan Rigaut, email=<gaetanrigaut.s@.com>"}, {name="Louis Thiry"}]
readme = "README.md"
requires-python = ">=3.9"


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
