[io]
name = "doublegyre"
performance_log = false
[io.output]
save_results = false
quantity = 10
directory = "results"
[io.plots]
show = true
save = false
quantity = 10
plots_directory = "plots"

[physics]
rho = 1000
slip_coef = 1.0
f0 = 9.375e-5           # mean coriolis (s^-1)
beta = 1.754e-11        # coriolis gradient (m^-1 s^-1)
bottom_drag_coefficient = nan

[model]
name = "Three Layer"
type = "QG"
h = [
    400,
    1100,
    2600,
]
g_prime = [
    9.81,
    0.025,
    0.0125,
]

[mesh]
nx = 32
ny = 64
dt = 4_000
[mesh.box]
unit = "m"
[mesh.box.x]
min = 0
max = 2560.0e3
[mesh.box.y]
min = 0
max = 5120.0e3

[windstress]
type = "cosine"
magnitude = 0.08 # (Pa m-1 kg s-2)
drag_coefficient = 1.3e-3
[windstress.data]