[physics]
rho = 1000
slip_coef = 1.0
f0 = 9.375e-5           # mean coriolis (s^-1)
beta = 1.754e-11        # coriolis gradient (m^-1 s^-1)
wind_stress_mag = 0.08   # Wind stress magnitude (Pa m-1 kg s-2)

[layers]
h = [
    400,
    1100,
    2600,
]
g_prime = [
    9.81,
    0.025,
    0.0125,
]

[grid]
nx = 32 # 128
ny = 64 # 256
dt = 4000
reference = "distance"
[grid.box]
unit = "m"
[grid.box.x]
min = 0
max = 2560.0e3
[grid.box.y]
min = 0
max = 5120.0e3