field = "pv"

[[source]]
folder = "output/g5k/double_gyre_3l_qg"
level = 0
[[source]]
folder = "output/g5k/double_gyre_3l_qg"
level = 1
[[source]]
folder = "output/g5k/double_gyre_3l_qg"
level = 2

[snapshots]
save = false
folder = "tmp"
saved_nb = 10