folders = [
    "output/g5k/one_layer_baroclinic_100km",
    "output/g5k/alpha_0_05",
    "output/g5k/two_layers_baroclinic_100km",
    "output/g5k/one_layer_baroclinic_100km",
    "output/g5k/alpha_0_1",
    "output/g5k/two_layers_baroclinic_100km",
    "output/g5k/one_layer_baroclinic_100km",
    "output/g5k/alpha_0_25",
    "output/g5k/two_layers_baroclinic_100km",
    "output/g5k/one_layer_baroclinic_100km",
    "output/g5k/alpha_0_5",
    "output/g5k/two_layers_baroclinic_100km",
]
display_sublayer = false
common_colorbar = false
[snapshots]
save = false
folder = "output/snapshots"
saved_nb = 25