folders = [
    "output/g5k/doublegyre_1l",
    "output/g5k/doublegyre_2l",
]
display_sublayer = false
common_colorbar = true
[snapshots]
save = false
folder = "output/snapshots/2L_100km_barotropic_"
saved_nb = 25