[io]
name = "Two Layers Model"
[io.output]
save=false
type = "quantity"           # "interval"
quantity = 100
# interval_duration = 3600  # seconds
directory = "tmp"

[physics]
rho = 1000
slip_coef = 1.0
f0 = 9.375e-5           # mean coriolis (s^-1)
beta = 1.754e-11
bottom_drag_coefficient = 3.60577e-8
Ro = 0.1

[simulation]
type = "simple-run"
duration = 2_389_333.3   # seconds
dt = 26                 # in seconds
[simulation.startup]

[model]
type = "QG"
prefix = "results_step_"
layers = [
    400,
    1100,
    2600,
]
reduced_gravity = [
    9.81,
    0.025,
    0.0125
]

[space]
nx = 128
ny = 256
unit = "m"
x_min = 0
x_max = 2560000
y_min = 0
y_max = 5120000

[windstress]
type = "cosine"
magnitude = 0.08
drag_coefficient = 0.0013

[perturbation]
type = "none"
perturbation_magnitude = 1e-3
