[io]
name = "Single Model Vortex"
performance_log = false
[io.output]
save_results = false
quantity = 10
directory = "results"
[io.plots]
show = true
save = false
quantity = 100
plots_directory = "plots"

[physics]
rho = 1000
slip_coef = 1.0
f0 = 9.375e-5           # mean coriolis (s^-1)
beta = 0                # coriolis gradient (m^-1 s^-1)
bottom_drag_coefficient = 0

[simulation]
duration = 8 # units of Tau
tau = 28 # in f0⁻¹, if nan: Tau is automatically computed
dt = 26 # in s, if nan: dt is automatically computed

[model]
name = "Two Layers"
prefix = "two_layers_"
type = "QGColinearSublayerStreamFunction"
h = [
    200,
    800
]
g_prime = [
    10.0,
    5e-2
]
colinearity_coef = 0.1 # Only relevant for modifiedd QG models

[space]
nx = 24
ny = 24
box_unit = "m"
[space.box]
unit = "m"
[space.box.x]
min = -150_000
max = 150_000
[space.box.y]
min = -150_000
max = 150_000

[windstress]
type = "none"
magnitude = nan # (Pa m-1 kg s-2)
drag_coefficient = nan
[windstress.data]

[perturbation]
type = "vortex-baroclinic"
perturbation_magnitude = 1e-3
