[io]
name = "Two Layers Model"
performance_log = false
[io.output]
save_results = true
quantity = 100
directory = "results_"

[physics]
rho = 1000
slip_coef = 1.0
f0 = 9.375e-5           # mean coriolis (s^-1)
beta = 0                # coriolis gradient (m^-1 s^-1)
bottom_drag_coefficient = 0

[simulation]
duration = 8 # units of Tau
reference= 'tau' # 'tau' or 'sec'
tau = 28 # in f0⁻¹, if nan: Tau is automatically computed
dt = 26 # in s, if nan: dt is automatically computed

[model]
name = "Two Layers"
prefix = "results_step_"
type = "QG"
h = [
    200,
    800
]
g_prime = [
    10.0,
    5e-2
]
[model.collinearity_coef]
# Section relevant for modified QG models only
type = "constant" # 'constant' or 'changing'
value = 0.1 # Only relevant for constant coefficients.
source_file = "data/coefficients.npz" # Only relevant for 'changing' coefficients.

[space]
nx = 192
ny = 192
box_unit = "m"
[space.box]
unit = "m"
[space.box.x]
min = -500_000
max = 500_000
[space.box.y]
min = -500_000
max = 500_000

[windstress]
type = "none"
magnitude = nan # (Pa m-1 kg s-2)
drag_coefficient = nan
[windstress.data]

[perturbation]
type = "vortex-baroclinic"
perturbation_magnitude = 1e-3
