[1L-baroclinic-30km]
field = "pv"
layer = 0
input = "one_layer_baroclinic_30km"
output = "1L_baroclinic_30km"
steps = [33084, 62492, 91898]
colorscale = "RdBu_r"

[2L-baroclinic-30km]
field = "pv"
layer = 0
input = "two_layers_baroclinic_30km"
output = "2L_baroclinic_30km"
steps = [33084, 62492, 91898]
colorscale = "RdBu_r"

[2L-baroclinic-30km-bottom]
field = "pv"
layer = 1
input = "two_layers_baroclinic_100km"
output = "2L_baroclinic_30km_bottom"
steps = [33084, 62492, 91898]
colorscale = "RdBu_r"

[1L-baroclinic-100km]
field = "pv"
layer = 0
input = "one_layer_baroclinic_100km"
output = "1L_baroclinic_100km"
steps = [33084, 62492, 91898]
colorscale = "RdBu_r"

[2L-baroclinic-100km]
field = "pv"
layer = 0
input = "two_layers_baroclinic_100km"
output = "2L_baroclinic_100km"
steps = [33084, 62492, 91898]
colorscale = "RdBu_r"

[2L-baroclinic-100km-bottom]
field = "pv"
layer = 1
input = "two_layers_baroclinic_100km"
output = "2L_baroclinic_100km_bottom"
steps = [33084, 62492, 91898]
colorscale = "RdBu_r"

[1L-barotropic-100km]
field = "pv"
layer = 0
input = "one_layer_barotropic_100km"
output = "1L_barotropic_100km"
steps = [33084, 62492, 91898]
colorscale = "RdBu_r"

[2L-barotropic-100km]
field = "pv"
layer = 0
input = "two_layers_barotropic_100km"
output = "2L_barotropic_100km"
steps = [33084, 62492, 91898]
colorscale = "RdBu_r"