[io]
name = "1_layer_200"
plot_frequency = nan # in days
performance_log = false
output_dir = "output/reduced_grav/200_vs_200_4000"

[physics]
rho = 1000
slip_coef = 1.0
f0 = 9.375e-5           # mean coriolis (s^-1)
beta = 0                # coriolis gradient (m^-1 s^-1)
bottom_drag_coefficient = 0

[[models]]
name = "One Layer"
type = "QG"
h = [
    200,
]
g_prime = [
    5e-2
]
[[models]]
name = "Multilayer"
type = "QG"
h = [
    200,
    800,
]
g_prime = [
    10.0,
    5e-2,
]

[mesh]
nx = 96
ny = 96
dt = 4_000
[mesh.box]
unit = "m"
[mesh.box.x]
min = -2_200_000
max = 2_200_000
[mesh.box.y]
min = -2_200_000
max = 2_200_000

[windstress]
type = "none"
magnitude = 0.08 # (Pa m-1 kg s-2)
drag_coefficient = 1.3e-3
[windstress.data]

[vortex]
type = "passive"
perturbation_magnitude = 1e-3
