[io]
name = "200_vs_200_800"
performance_log = false
[io.output]
save_results = true
quantity = 10
directory = "output"
[io.plots]
show = false
save = true
quantity = 2
plots_directory = "output/plots"

[physics]
rho = 1000
slip_coef = 1.0
f0 = 9.375e-5           # mean coriolis (s^-1)
beta = 0                # coriolis gradient (m^-1 s^-1)
bottom_drag_coefficient = 0

[[models]]
name = "One Layer"
type = "QG"
h = [
    200,
]
g_prime = [
    5e-2
]
[[models]]
name = "Multilayer"
type = "QG"
h = [
    200,
    800,
]
g_prime = [
    10.0,
    5e-2,
]

[mesh]
nx = 24
ny = 24
dt = 4_000
[mesh.box]
unit = "m"
[mesh.box.x]
min = -2_200_000
max = 2_200_000
[mesh.box.y]
min = -2_200_000
max = 2_200_000

[windstress]
type = "none"
magnitude = 0.08 # (Pa m-1 kg s-2)
drag_coefficient = 1.3e-3
[windstress.data]

[vortex]
type = "passive"
perturbation_magnitude = 1e-3
