[io]
name = "vortexgyre"
plot_frequency = nan # in days
performance_log = false
output_dir = "output"

[physics]
rho = 1000
slip_coef = 1.0
f0 = 9.375e-5           # mean coriolis (s^-1)
beta = 0                # coriolis gradient (m^-1 s^-1)
bottom_drag_coefficient = 0

[layers]
h = [
    1000,
]
g_prime = [
    10.0,
]

[grid]
nx = 96
ny = 96
dt = 4_000
box_unit = "m"
[grid.box]
[grid.box.x]
min = -50_000
max = 50_000
[grid.box.y]
min = -50_000
max = 50_000

[windstress]
type = "none"
magnitude = 0.08 # (Pa m-1 kg s-2)
drag_coefficient = 1.3e-3
[windstress.data]