[io]
name = "na"
plot_frequency = nan # in days
performance_log = false
output_dir = "output"

[physics]
rho = 1000
slip_coef = 1.0
f0 = 9.375e-5           # mean coriolis (s^-1)
beta = 1.754e-11        # coriolis gradient (m^-1 s^-1)
bottom_drag_coefficient = nan

[layers]
h = [
    400,
    1100,
    2600,
]
g_prime = [
    9.81,
    0.025,
    0.0125,
]

[mesh]
nx = 1024 # 128
ny = 512 # 256
dt = 4000
box_unit = "deg"
[mesh.box]
[mesh.box.x]
min = -98
max = nan
[mesh.box.y]
min = 9
max = 48

[bathymetry]
htop_ocean = -250
lake_min_area = 40_000
island_min_area = 1_000
interolation = "linear"
[bathymetry.data]
folder = "data"
URL = "https://www.di.ens.fr/louis.thiry/AN_etopo1.mat"
longitude = "lon_bathy"
latitude = "lat_bathy"
elevation = "bathy"

[windstress]
type = "data"
magnitude = nan # (Pa m-1 kg s-2)
drag_coefficient = nan
[windstress.data]
URL = "http://iridl.ldeo.columbia.edu/SOURCES/.HELLERMAN/data.nc"
folder = "data"
data = "tau"
longitude = "X"
latitude = "Y"
time = "T"
field_1 = "taux"
field_2 = "tauy"
method="linear"