name: Ruff Linting
on:
  pull_request:

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Clone code
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install ruff
        run: python -m pip install ruff
      - name: Run ruff
        run: python -m ruff check --force-exclude
