name: Run Tests
on:
  pull_request:

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone code
        uses: actions/checkout@v4
      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
            auto-update-conda: true
            channels: conda-forge
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install nox
        run: python -m pip install nox
      - name: Run Nox
        run: python -m nox
