name: Run Tests
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            auto-activate-base: true
      - name: Install nox
        run: conda install nox
      - name: Run Nox
        run: nox
