name: Run Tests
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
            auto-update-conda: true
            channels: conda-forge
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install nox
        run: python -m pip install nox
      - name: Run Nox
        run: python -m nox
