name: Run Tests
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
            python-version: 3.12
            activate-environment: ""
            channels: conda-forge
            auto-activate-base: true
      - name: Install nox
        run: python -m pip install nox
      - name: Run Nox
        run: python -m nox
