name: Run Testscond
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            python-version: '3.12'
            auto-activate-base: true
      - name: Install nox
        run: python -m pip install nox
      - name: Run Nox
        run: python -m nox
